<?php
/**
 * Implements hook_enable().
 */
function crm_core_report_enable() {
  $item = array(
    'link_path' => 'crm/reports',
    'link_title' => 'Reports',
    'menu_name' => 'crm-core-menu',
    'weight' => 2,
  );
  menu_link_save($item);
}

/**
 * Implements hook_disable().
 */
function crm_core_report_disable() {
  $links = menu_load_links('crm-core-menu');
  foreach ($links as $link) {
    if ($link['link_path'] == 'crm/reports') {
      menu_link_delete($link['mlid']);
    }
  }
}
