<?php
// $Id$

/**
 * @file
 * Provides contact entities and basic CRM functionality.
 */


/**
 * Implements hook_entity_info().
 */
function crm_entity_info() {
  $return = array(
    'contact' => array(
      'label' => t('Contact'),
      'controller class' => 'CRMContactController',
      'base table' => 'crm_contact',
      'uri callback' => 'crm_contact_uri',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'contact_id',
        'bundle' => 'type',
      ),
      'bundle keys' => array(
        'bundle' => 'type',
      ),
      'view modes' => array(
        'full' => array(
          'label' => t('Contact'),
          'custom settings' => FALSE,
        ),
      ),
    ),
  );

  foreach (crm_contact_type_get_name() as $type => $name) {
    $return['contact']['bundles'][$type] = array(
      'label' => $name,
      'admin' => array(
        'path' => 'admin/crm/contact-types/manage/%crm_contact_type',
        'real path' => 'admin/crm/contact-types/manage/' . str_replace('_', '-', $type),
        'bundle argument' => 4,
        'access arguments' => array('administer contact types'),
      ),
    );
  }

  return $return;
}

/**
 * Entity uri callback.
 */
function crm_contact_uri($contact) {
  return array(
    'path' => 'crm/contact/' . $contact->cid,
  );
}

/**
 * Implements hook_permission().
 */
function crm_permission() {
  return array(
    'administer contact types' => array(
        'title' => t('Administer Contact Types'),
        'description' => t('Allows the user to edit the types of contact such as Individual, Organization, etc.'),
    ),
  );
}

/**
 * Implements hook_views_api().
 */
function crm_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'crm') . '/includes/views',
  );
}

/**
 * Implements hook_field_extra_fields().
 */
// function user_field_extra_fields() {
//   $return['user']['user'] = array(
//     'form' => array(
//       'account' => array(
//         'label' => 'User name and password',
//         'description' => t('User module account form elements'),
//         'weight' => -10,
//       ),
//       'timezone' => array(
//         'label' => 'Timezone',
//         'description' => t('User module timezone form element.'),
//         'weight' => 6,
//       ),
//     ),
//     'display' => array(
//       'summary' => array(
//         'label' => 'History',
//         'description' => t('User module history view element.'),
//         'weight' => 5,
//       ),
//     ),
//   );
// 
//   return $return;
// }




/**
 * Implements hook_menu().
 */
function crm_menu() {
  
  $items = array();
  
  // Administration pages.
  $items['crm/admin/contact-types/manage'] = array(
    'title' => 'Manage contact types',
    'page callback' => 'crm_contact_types_manage',
    'access arguments' => array('administer contact types'),
    'file' => 'contact_types.inc',
  );
  $items['crm/admin/contact-types/manage/%crm_contact_type'] = array(
    'title' => 'Edit contact type',
    'title callback' => 'crm_contact_type_title',
    'title arguments' => array(4),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('crm_contact_type_form', 4),
    'access arguments' => array('administer contact types'),
    'file' => 'contact_types.inc',
  );
  $items['crm/admin/contact-types/manage/%crm_contact_type/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['crm/admin/contact-types/manage/%crm_contact_type/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('crm_contact_type_delete_confirm', 4),
    'access arguments' => array('administer contact types'),
    'type' => MENU_CALLBACK,
    'file' => 'contact_types.inc',
  );

 
/*  
  $items['crm/%contact/%crm_contact'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_profile_form', 1),
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'user.pages.inc',
  );*/

  return $items;
}


/**
 * Implements hook_admin_paths().
 */
function crm_admin_paths() {
  $paths = array(
    'crm/admin/*' => TRUE,
  );
  return $paths;
}


/**
 * Returns an array of contact type objects keyed by type.
 */
function crm_contact_types() {
  // First check the static cache for a contact types array.
  $contact_types = &drupal_static(__FUNCTION__);

  // If it did not exist, fetch the types now.
  if (!isset($contact_types)) {
    $contact_types = db_query('SELECT * FROM {crm_contact_type}')->fetchAllAssoc('type');
  }

  return $contact_types;
}


/**
 * Returns the human readable name of any or all contact types.
 *
 * @param $type
 *  [optional] - Specify the type whose name to return.
 * @return
 *  If $type is specified, a string containing the human
 *  readable name of the type.
 *  If $type isn't specified an array containing all human
 *  readable names keyed on the machine type.
 */
function crm_contact_get_name($type = NULL) {
  $contact_types = crm_contact_types();

  // If type is set return the name if it exists
  if ($type !== NULL && isset($contact_types[$type])) {
    return $contact_types[$type]->name;
  }
  else {
    return FALSE;
  }

  // Otherwise return a mapping of type => name
  foreach ($contact_types as $key => $value) {
    $contact_types[$key] = $value->name;
  }

  return $contact_types;
}




function crm_contact_type_set_defaults($info = array()) {
  $type = &drupal_static(__FUNCTION__);

  if (!isset($type)) {
    $type = new stdClass();
    $type->type = '';
    $type->name = '';
    $type->description = '';
    $type->custom = 0;
    $type->modified = 0;
    $type->is_new = 1;
  }

  $new_type = clone $type;
  $info = (array) $info;
  foreach ($info as $key => $data) {
    $new_type->$key = $data;
  }
  $new_type->orig_type = isset($info['type']) ? $info['type'] : '';

  return $new_type;
}
