<?php
// $Id$

/**
 * @file
 * Provides contact entities and basic CRM functionality.
 */


/**
 * Implements hook_entity_info().
 */
function crm_entity_info() {
  $return = array(
    'crm_contact' => array(
      'label' => t('Contact'),
      'controller class' => 'CRMContactController',
      'base table' => 'crm_contact',
      'uri callback' => 'crm_contact_uri',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'contact_id',
        'bundle' => 'type',
      ),
      'bundle keys' => array(
        'bundle' => 'type',
      ),
      'bundles' => array(),
      'view modes' => array(
        'full' => array(
          'label' => t('Contact'),
          'custom settings' => FALSE,
        ),
      ),
    ),
  );

  foreach (crm_contact_type_get_name() as $type => $name) {
    $return['crm_contact']['bundles'][$type] = array(
      'label' => $name,
      'admin' => array(
        'path' => 'crm/admin/contact/types/%crm_contact_type',
        'real path' => 'crm/admin/contact/types/' . str_replace('_', '-', $type),
        'bundle argument' => 4,
        'access arguments' => array('administer contact types'),
      ),
    );
  }

  return $return;
}


/**
 * Entity uri callback.
 */
function crm_contact_uri($contact) {
  return array(
    'path' => 'crm/contact/' . $contact->cid,
  );
}


/**
 * Implements hook_permission().
 */
function crm_permission() {
  return array(
    'administer contact types' => array(
      'title' => t('Administer Contact Types'),
      'description' => t('Allows the user to edit the types of contact such as Individual, Organization, etc.'),
    ),
    'add contacts' => array(
      'title' => t('Add Contacts'),
      'description' => t('Allows the user to add contact to the CRM.'),
    ),
  );
}


/**
 * Implements hook_views_api().
 */
function crm_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'crm') . '/includes/views',
  );
}


/**
 * Implemenets hook_theme().
 */
function crm_theme() {
  $theme = array(
    'crm_contact_type_overview' => array(
      'variables' => array('contact_type' => NULL),
      'file' => 'theme/crm_contact_type.theme.inc',
    ),
    'crm_contact_add_list' => array(
      'variables' => array('content' => array()),
      'file' => 'theme/crm_contact.theme.inc',
    ),
  );

  return $theme;
}

/**
 * Implements hook_field_extra_fields().
 */
// function user_field_extra_fields() {
//   $return['user']['user'] = array(
//     'form' => array(
//       'account' => array(
//         'label' => 'User name and password',
//         'description' => t('User module account form elements'),
//         'weight' => -10,
//       ),
//       'timezone' => array(
//         'label' => 'Timezone',
//         'description' => t('User module timezone form element.'),
//         'weight' => 6,
//       ),
//     ),
//     'display' => array(
//       'summary' => array(
//         'label' => 'History',
//         'description' => t('User module history view element.'),
//         'weight' => 5,
//       ),
//     ),
//   );
// 
//   return $return;
// }



/**
 * Implements hook_menu().
 */
function crm_menu() {
  $items = array();
  
  /*
   * Contacts
   */
  $items['crm/contact/%crm_contact'] = array(
    'title' => 'Contact',
    'page callback' => 'crm_contact_view',
    'page arguments' => array(2),
    'access arguments' => array('view contacts'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pages/contact.pages.inc',
  );
  $items['crm/contact/add'] = array(
    'title' => 'Add a contact',
    'description' => 'Add a new contact to the CRM.',
    'page callback' => 'crm_contact_add_page',
    'access arguments' => array('add contacts'),
    'type' => MENU_LOCAL_ACTION,
    'weight' => 10,
    'file' => 'pages/contact.pages.inc',
  );
  foreach (crm_contact_types() as $type => $contact_type) {
    $items['crm/contact/add/' . $type] = array(
      'title' => 'Add @type',
      'title arguments' => array('@type' => $contact_type->name),
      'description' => $contact_type->description,
      'page callback' => 'crm_contact_form_wrapper',
      'page arguments' => array(crm_contact_type_new($type)),
      'access arguments' => array('add contacts'),
      'file' => 'pages/contact.pages.inc',
    );
  }

/*
  $items['admin/commerce/products/add'] = array(
    'title' => 'Add a product',
    'description' => 'Add a new product for sale.',
    'page callback' => 'commerce_product_ui_add_page',
    'access callback' => 'commerce_product_ui_product_add_any_access',
    'type' => MENU_LOCAL_ACTION,
    'weight' => 10,
    'file' => 'includes/commerce_product_ui.products.inc',
  );
  foreach (commerce_product_types() as $type => $product_type) {
    $items['admin/commerce/products/add/' . $type] = array(
      'title' => 'Create @name',
      'title arguments' => array('@name' => $product_type->name),
      'description' => $product_type->description,
      'page callback' => 'commerce_product_ui_product_form_wrapper',
      'page arguments' => array(commerce_product_new($type)),
      'access callback' => 'commerce_product_access',
      'access arguments' => array('create', $type),
      'file' => 'includes/commerce_product_ui.products.inc',
    );
  }
 */

  /*
   * Contact types
   */
  $items['crm/admin/contact/types'] = array(
    'title' => 'Manage contact types',
    'page callback' => 'crm_contact_types_overview',
    'access arguments' => array('administer contact types'),
    'file' => 'pages/contact_types.pages.inc',
  );
  $items['crm/admin/contact/types/add'] = array(
    'title' => 'Add contact type',
    'page callback' => 'crm_contact_type_form_wrapper',
    'page arguments' => array(crm_contact_type_new()),
    'access arguments' => array('administer contact types'),
    'type' => MENU_LOCAL_ACTION | MENU_VISIBLE_IN_BREADCRUMB,
    'file' => 'pages/contact_types.pages.inc',
  );
  $items['crm/admin/contact/types/%crm_contact_type'] = array(
    'title' => 'Edit contact type',
    'title callback' => 'crm_contact_type_title',
    'title arguments' => array(4),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('crm_contact_type_form', 4),
    'access arguments' => array('administer contact types'),
    'file' => 'pages/contact_types.pages.inc',
  );
  $items['crm/admin/contact/types/%crm_contact_type/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  $items['crm/admin/contact/types/%crm_contact_type/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('crm_contact_type_delete_confirm', 4),
    'access arguments' => array('administer contact types'),
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
    'file' => 'pages/contact_types.pages.inc',
    'weight' => 10,
  );

 
/*  
  $items['crm/%contact/%crm_contact'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_profile_form', 1),
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'user.pages.inc',
  );*/

  return $items;
}


/**
 * Implements hook_menu_alter().
 */
function crm_menu_alter(&$items) {
  // Transform the field UI tabs into contextual links.
  $items['crm/admin/contact/types/%crm_contact_type/fields']['context'] = MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE;
  $items['crm/admin/contact/types/%crm_contact_type/display']['context'] = MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE;
}


/**
 * Implements hook_admin_paths().
 */
function crm_admin_paths() {
  $paths = array(
    'crm/admin' => TRUE,
    'crm/admin/*' => TRUE,
    'crm/admin/contact/types' => TRUE,
    'crm/admin/contact/types/*' => TRUE,
  );

  return $paths;
}


/**
 * Returns an array of contact type objects keyed by type.
 */
function crm_contact_types() {
  // First check the static cache for a contact types array.
  $contact_types = &drupal_static(__FUNCTION__);

  // If it did not exist, fetch the types now.
  if (!isset($contact_types)) {
    $contact_types = db_query('SELECT * FROM {crm_contact_type}')->fetchAllAssoc('type');
  }

  return $contact_types;
}


/**
 * Returns the human readable name of any or all contact types.
 *
 * @param $type
 *  [optional] - Specify the type whose name to return.
 * @return
 *  If $type is specified, a string containing the human
 *  readable name of the type.
 *  If $type isn't specified an array containing all human
 *  readable names keyed on the machine type.
 */
function crm_contact_type_get_name($type = NULL) {
  $contact_types = crm_contact_types();
 
  // If type is set return the name if it exists
  if (!empty($type)) {
    if (isset($contact_types[$type])) {
      return $contact_types[$type]->name;
    }
    else {
      return FALSE;
    }
  }
  
  // Otherwise return a mapping of type => name
  foreach ($contact_types as $key => $value) {
    $contact_types[$key] = $value->name;
  }

  return $contact_types;
}


/**
 * Return a new contact type with initialize fields.
 */
function crm_contact_type_new($type = '') {
  return (object) array(
    'type' => $type,
    'name' => '',
    'description' => '',
    'help' => '',
  );
}


/**
 * Loads a contact type.
 * 
 * @param $type
 *   The machine-readable name of the contact type.
 */
function crm_contact_type_load($type) {
  return db_query("SELECT * FROM {crm_contact_type} WHERE type = :type", array(':type' => $type))->fetchObject();
}


/**
 * Saves a contact type.
 */
function crm_contact_type_save($contact_type) {
  $op = drupal_write_record('crm_contact_type', $contact_type, empty($contact_type->is_new) ? 'type' : array());
  menu_rebuild();

  // If this is a new contact type and the insert did not fail...
  if (!empty($contact_type->is_new) && $op !== FALSE) {
    // Notify the field API that a new bundle has been created.
    field_attach_create_bundle('crm_contact', $contact_type->type);

    // Add base fields to the contact
    crm_initialize_contact_type($contact_type->type);

    // Notify other modules that a new contact type has been created.
    module_invoke_all('crm_contact_type_insert', $contact_type);
  }
  else {
    // Notify other modules that an existing contact type has been updated.
    module_invoke_all('crm_contact_type_update', $contact_type);
  }

  return $op;
}


function crm_contact_type_set_defaults($info = array()) {
  $type = &drupal_static(__FUNCTION__);

  if (!isset($type)) {
    $type = new stdClass();
    $type->type = '';
    $type->name = '';
    $type->description = '';
    $type->custom = 0;
    $type->modified = 0;
    $type->is_new = 1;
  }

  $new_type = clone $type;
  $info = (array) $info;
  foreach ($info as $key => $data) {
    $new_type->$key = $data;
  }
  $new_type->orig_type = isset($info['type']) ? $info['type'] : '';

  return $new_type;
}


/**
 * Initialize new contact type with basic fields.
 */
function crm_initialize_contact_type($type) {
  $fields = array();

  // Name field
  $fields[] = array(
    'field_name' => 'contact_name',
    'type' => 'text',
    'entity_types' => array('crm_contact'),
    'translatable' => FALSE,
    'locked' => TRUE,
  );

  // Image field
  $fields[] = array(
    'field_name' => 'contact_image',
    'type' => 'image',
    'entity_types' => array('crm_contact'),
    'translatable' => FALSE,
    'locked' => TRUE,
  );

  // Address field
  $fields[] = array(
    'field_name' => 'contact_address',
    'type' => 'addressfield',
    'entity_types' => array('crm_contact'),
    'translatable' => FALSE,
    'locked' => TRUE,
  );

  // Email and phone fields
  // @TODO consider switching these over to e-mail and phone fields once the modules are installed
  $fields[] = array(
    'field_name' => 'contact_email',
    'type' => 'text',
    'cardinality' => FIELD_CARDINALITY_UNLIMITED,
    'entity_types' => array('crm_contact'),
    'translatable' => FALSE,
    'locked' => TRUE,
  );

  $fields[] = array(
    'field_name' => 'contact_phone',
    'type' => 'text',
    'cardinality' => FIELD_CARDINALITY_UNLIMITED,
    'entity_types' => array('crm_contact'),
    'translatable' => FALSE,
    'locked' => TRUE,
  );

  // Create the fields if they don't exist
  foreach ($fields as $field) {
    $info = field_info_field($field['field_name']);
    if (empty($info)) {
      field_create_field($field);
    }
  }

  // Create field instances for the type if they don't exist
  $instances = array();

  $instances[] = array(
    'field_name' => 'contact_name',
    'entity_type' => 'crm_contact',
    'bundle' => $type,
    'label' => t('Name'),
    'required' => TRUE,
    'settings' => array(),
    'widget' => array(
      'type' => 'text_textfield',
    ),
    'display' => array(),
  );

  $instances[] = array(
    'field_name' => 'contact_image',
    'entity_type' => 'crm_contact',
    'bundle' => $type,
    'label' => t('Image'),
    'required' => FALSE,
    'settings' => array(),
    'widget' => array(
      'type' => 'image_image',
    ),
    'display' => array(),
  );

  $instances[] = array(
    'field_name' => 'contact_address',
    'entity_type' => 'crm_contact',
    'bundle' => $type,
    'label' => t('Address'),
    'required' => FALSE,
    'settings' => array(),
    'widget' => array(
      'type' => 'addressfield_standard',
    ),
    'display' => array(),
  );

  $instances[] = array(
    'field_name' => 'contact_email',
    'entity_type' => 'crm_contact',
    'bundle' => $type,
    'label' => t('E-Mail Address'),
    'required' => FALSE,
    'settings' => array(),
    'widget' => array(
      'type' => 'text_textfield',
    ),
    'display' => array(),
  );

  $instances[] = array(
    'field_name' => 'contact_phone',
    'entity_type' => 'crm_contact',
    'bundle' => $type,
    'label' => t('Phone Number'),
    'required' => FALSE,
    'settings' => array(),
    'widget' => array(
      'type' => 'text_textfield',
    ),
    'display' => array(),
  );

  // Create field instances if they don't exist
  foreach ($instances as $instance) {
    $info_instance = field_info_instance('crm_contact', $instance['field_name'], $type);
    if (empty($info_instance)) {
      field_create_instance($instance);
    }
  }
}


/**
* Checks to see if a given contact type already exists.
*
* @param $type
* The string to match against existing types.
*
* @return
* TRUE or FALSE indicating whether or not the contact type exists.
*/
function crm_contact_type_validate_unique($type) {
  // Look for a match of the type.
  $match_id = db_query('SELECT type FROM {crm_contact_type} WHERE type = :type', array(':type' => $type))->fetchField();
  return !$match_id;
}


function crm_contact_save($contact) {
  return entity_get_controller('crm_contact')->save($contact);
}


function crm_contact_load($contact_id) {
  $contacts = crm_contact_load_multiple(array($contact_id));
  return $contacts ? reset($contacts) : FALSE;
}


function crm_contact_load_multiple($contact_ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('crm_contact', $contact_ids, $conditions, $reset);
}