<?php
/**
 * @file
 * CRM Core Devel.
 */

/**
 * Implements hook_menu().
 */
function crm_core_devel_menu() {
  $items['admin/structure/crm/devel'] = array(
    'title' => 'CRM Devel',
    'description' => 'Helper functions, pages, and blocks to assist Drupal developers.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('crm_core_devel_admin_settings'),
    'file' => 'crm_core_devel.admin.inc',
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Exports contacts and activities to specified file.
 *
 * @param string $filename
 *   File name.
 */
function crm_core_devel_export($filename) {

  if (!empty($filename) && !is_file($filename)) {
    $export = array();

    $ids = db_select('crm_core_contact')
      ->fields('crm_core_contact', array('contact_id'))->execute()->fetchCol();
    $contacts = crm_core_contact_load_multiple($ids);
    foreach ($contacts as $contact) {
      $export['crm_core_contact'][$contact->contact_id] = entity_export('crm_core_contact', $contact);
    }
    $ids = db_select('crm_core_activity')
      ->fields('crm_core_activity', array('activity_id'))->execute()
      ->fetchCol();
    $activities = crm_core_activity_load_multiple($ids);
    foreach ($activities as $activity) {
      $export['crm_core_activity'][$activity->activity_id] = entity_export('crm_core_activity', $activity);
    }
    require_once DRUPAL_ROOT . '/includes/utility.inc';
    $file = new SplFileObject($filename, 'a');
    $file->fwrite(drupal_var_export($export));
  }
}
