<?php

/**
 * @file
 * Install, update, and uninstall functions for the CRM Core UI module.
 */

/**
 * Implements hook_install().
 */
function crm_core_ui_install() {
  db_query("UPDATE {system} SET weight = 15 WHERE name = 'crm_core_ui'");
  $menus = crm_core_ui_get_menus();
  foreach($menus as $menu) {
    menu_save($menu);
  }
  // Rebuild menu so Activity Types menu element will be placed under CRM.
  menu_rebuild();
}
