<?php

/**
 * Implements hook_menu().
 */
function crm_ui_menu() {
  $items = array();

  /**
   * Base CRM menu
   */
  $items['crm'] = array(
    'title' => 'CRM',
    'page callback' => 'crm_ui_placeholder',
    'access arguments' => array('view crm dashboard'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pages/crm_ui.pages.inc',
  );

  $items['crm/dashboard'] = array(
    'title' => 'Dashboard',
    'weight' => -10,
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE,
  );

  $items['admin/structure/crm'] = array(
    'title' => 'CRM',
    'description' => 'Manage contact types, activity types, and contact relationship types.',
		'page callback' => 'crm_ui_admin_dashboard',
		'access arguments' => array('access administration pages'),
    'file' => 'pages/crm_ui.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function crm_ui_menu_alter(&$items) {
  // Transform the field UI tabs into contextual links.
  
  $items['admin/structure/crm/activity-types']['type'] = MENU_LOCAL_TASK;

  // Make Views menu item local task.
  $items['crm/contact/%/activity/add']['type'] = MENU_LOCAL_ACTION;
  $items['crm/contact/%/activity/add']['title'] = t('Add Activity');

  // Alter Views menu item.
  $items['crm/contact/%/activity']['title'] = t('Activity');
  $items['crm/contact/%/activity']['type'] = MENU_LOCAL_TASK;
  $items['crm/contact/%/activity']['context'] = MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE;

}

/**
 * Implements hook_admin_paths().
 */
function crm_ui_admin_paths() {
  $paths = array(
    'crm/admin' => TRUE,
    'crm/admin/*' => TRUE,
  );

  return $paths;
}

/**
 * Implements hook_block_info().
 */
function crm_ui_block_info() {
  $blocks['navigation'] = array(
    'info' => t('CRM Navigaiton'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function crm_ui_block_view($delta) {
  module_load_include('inc', 'crm_ui', 'includes/crm_ui.blocks');

  $sub_func = 'crm_ui_block_' . $delta . '_subject';
  $con_func = 'crm_ui_block_' . $delta . '_content';

  if(!function_exists($sub_func) || !function_exists($con_func)) {
    return array();
  }

  return array(
    'subject' => $sub_func(),
    'content' => $con_func(),
  );
}

/**
 * Implements hook_views_api().
 */
function crm_ui_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'crm_ui') . '/includes/views',
  );
}

/**
 * A placeholder function.
 */
 function crm_ui_placeholder() {
  return "This is a placeholder.";
 }