<?php

/**
 * Implements hook_menu().
 */
function crm_ui_menu() {
  $items = array();

  /**
   * Base CRM menu
   */
  $items['crm'] = array(
    'title' => 'CRM',
    'page callback' => 'crm_ui_placeholder',
    'access arguments' => array('view crm dashboard'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pages/crm_ui.pages.inc',
  );

  $items['crm/dashboard'] = array(
    'title' => 'Dashboard',
    'weight' => -10,
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE,
  );

  $items['admin/structure/crm'] = array(
    'title' => 'CRM',
    'description' => 'Manage contact types, activity types, and contact relationship types.',
    'page callback' => 'crm_ui_admin_dashboard',
    'access arguments' => array('access administration pages'),
    'file' => 'pages/crm_ui.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function crm_ui_menu_alter(&$items) {
  // Transform the field UI tabs into contextual links.
  $items['admin/structure/crm/activity-types']['type'] = MENU_LOCAL_TASK;
  $items['admin/structure/crm/contact-types']['type'] = MENU_LOCAL_TASK;

  // Make Views menu item local task.
  $items['crm/contact/%/activity/add']['type'] = MENU_LOCAL_ACTION;
  $items['crm/contact/%/activity/add']['title'] = t('Add Activity');
  $items['crm/contact/%/activity/add']['tab_root'] = 'crm/contact/%/activity';

  // Set tab_root for views local actions.
  $items['crm/contact/%/activity']['tab_root'] = 'crm/contact/%';
  $items['crm/contact/%/revisions']['tab_root'] = 'crm/contact/%';

  // Alter Views menu item.
  $items['crm/contact/%/activity']['title'] = t('Activity');
  $items['crm/contact/%/activity']['type'] = MENU_LOCAL_TASK;
  $items['crm/contact/%/activity']['context'] = MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE;
}

/**
 * Implements hook_permission().
 */
function crm_ui_permission() {
  return array(
    'view crm dashboard' => array(
      'title' => t('View CRM dashboard'),
      'description' => t('Use dashboard.'),
    ),
  );
}

/**
 * Implements hook_disable().
 */
function crm_ui_disable() {
  variable_del('crm_ui_plid');
}

/**
 * Implements hook_theme().
 */
function crm_ui_theme() {
  return array(
    'crm_ui_ctools_dropbutton' => array(
      'variables' => array('ops_count' => NULL, 'links' => array(), 'index' => NULL)
    )
  );
}

/**
 * Implements hook_admin_paths().
 */
function crm_ui_admin_paths() {
  $paths = array(
    'crm/admin' => TRUE,
    'crm/admin/*' => TRUE,
  );

  return $paths;
}

/**
 * Implements hook_block_info().
 */
function crm_ui_block_info() {
  $blocks['navigation'] = array(
    'info' => t('CRM Navigaiton'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function crm_ui_block_view($delta) {
  module_load_include('inc', 'crm_ui', 'includes/crm_ui.blocks');

  $sub_func = 'crm_ui_block_' . $delta . '_subject';
  $con_func = 'crm_ui_block_' . $delta . '_content';

  if(!function_exists($sub_func) || !function_exists($con_func)) {
    return array();
  }

  return array(
    'subject' => $sub_func(),
    'content' => $con_func(),
  );
}

/**
 * A placeholder function.
 */
 function crm_ui_placeholder() {
  return "This is a placeholder.";
 }

/**
 * Implements hook_views_pre_render()
 */
function crm_ui_views_pre_render($view) {
  if($view->name == 'crm_activities_by_contact') {
    crm_ui_ctools_add_dropbutton_files();
  }
}

/**
 * Additional function that adds special CSS/JS files for dropbuttons
 */
function crm_ui_ctools_add_dropbutton_files() {
  // Add needed files
  ctools_add_js('dropbutton');
  ctools_add_css('dropbutton');
  ctools_add_css('button');

  // Add views & seven files
  views_add_css('views-admin');
  views_add_css('views-admin.ctools');
  views_add_css('views-admin.seven');
  drupal_add_css(drupal_get_path('module', 'crm_ui') . '/css/crm_ui.admin.css');
}

 /**
  * Theme function for operation links
  */
function theme_crm_ui_ctools_dropbutton($variables) {
  $output = '';

  $ops_count = $variables['ops_count'];
  $links = $variables['links'];
  $index = $variables['index'];

  if(is_array($links) && count($links)) {
    $item_list = array();
    for($i = count($links) - $ops_count; $i < count($links); $i++) {
       $item_list['items'][] = $links[$i];
    }

    $class = 'ctools-no-js ctools-dropbutton ctools-button';
    $output .= '<div class="' . $class . '" id="ctools-button-' . $index . '">';
    $output .= '<div class="ctools-link">';
    $output .= '<a href="#" class="ctools-twisty ctools-text">' . t('open') . '</a>';
    $output .= '</div>';
    $output .= '<div class="ctools-content">';
    $output .= theme('item_list', $item_list);
    $output .= '</div>';
    $output .= '</div>';
  }

  return $output;
}

/**
 * Helper function which retrieves CRM plid.
 *
 * Helps to build Navigation menu.
 */
function crm_ui_get_crm_mlid() {
  $plid = variable_get('crm_ui_plid', -1);

  if (empty($plid) || $plid == -1) {
    $crm_plid = menu_link_get_preferred('crm', 'navigation');
    $plid = $crm_plid['mlid'];
    variable_set('crm_ui_plid', $plid);
  }

  return $plid;
}