<?php

/**
 * @file
 * Provides a user interface for CRM Core Contact.
 */

/**
 * Implements hook_menu().
 */
function crm_core_contact_ui_menu() {
  $items = array();

  $items['crm-core/contact/%crm_core_contact/revert/%'] = array(
    'title' => 'Contact',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('crm_core_contact_ui_revert_form', 2, 4),
    'access callback' => 'entity_access',
    'access arguments' => array('revert', 'crm_core_contact', 2),
    'type' => MENU_CALLBACK,
    'file' => 'crm_core_contact_ui.pages.inc',
  );

  /*
   * Contact Debug
   */
  if (module_exists('devel')) {
    $items['crm-core/contact/%crm_core_contact/devel'] = array(
      'title' => 'Devel',
      'page callback' => 'crm_core_contact_devel_load_object',
      'page arguments' => array(2),
      'access arguments' => array('access devel information'),
      'type' => MENU_LOCAL_TASK,
      'weight' => 100,
    );

    $items['crm-core/contact/%crm_core_contact/devel/load'] = array(
      'title' => 'Load',
      'type' => MENU_DEFAULT_LOCAL_TASK,
    );

    $items['crm-core/contact/%crm_core_contact/devel/render'] = array(
      'title' => 'Render',
      'page callback' => 'crm_core_contact_devel_render_object',
      'page arguments' => array(2),
      'access arguments' => array('access devel information'),
      'type' => MENU_LOCAL_TASK,
      'weight' => 100,
    );
  }

  return $items;
}

/**
 * Implements hook_views_api().
 */
function crm_core_contact_ui_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'crm_core_contact_ui') . '/views',
  );
}

/**
 * Implements hook_menu_alter().
 */
function crm_core_contact_ui_menu_alter(&$items) {
  $items['admin/structure/crm-core/contact-types']['type'] = MENU_LOCAL_TASK;
  $dashboard_enabled = variable_get('crm_core_dashboard_enabled', FALSE);
  if (!$dashboard_enabled) {
    $items['crm-core/contact']['type'] = MENU_DEFAULT_LOCAL_TASK;
  }
}

/**
 * Implements hook_theme().
 */
function crm_core_contact_ui_theme() {
  $theme = array(
    'crm_core_contact_ui_add_list' => array(
      'variables' => array('content' => array()),
      'file' => 'crm_core_contact_ui.pages.inc',
      'template' => 'crm-core-contact-ui-add-list',
    ),
    'crm_core_contact_ui_revsions' => array(
      'variables' => array('contact_revisions' => array()),
    ),
  );

  return $theme;
}

/**
 * Implements hook_admin_menu_map().
 *
 * Expands contact types at Structure > CRM Core > CRM Core Contact types.
 */
function crm_core_contact_ui_admin_menu_map() {

  $contact_types = array_keys(crm_core_contact_types());
  $map = array();
  $map['admin/structure/crm-core/contact-types/manage/%crm_core_contact_type'] = array(
    'parent' => 'admin/structure/crm-core/contact-types',
    'hide' => 'admin/structure/crm-core/contact-types/list',
    'arguments' => array(
      array(
        '%entity_object' => $contact_types,
        '%crm_core_contact_type' => $contact_types,
      ),
    ),
  );

  return $map;
}

/**
 * Implements hook_entity_type_build().
 *
 * Add field_ui_base_route.
 */
function crm_core_contact_ui_entity_type_build(&$entity_types) {
  $entity_types['crm_core_contact']->set('field_ui_base_route','entity.crm_core_contact_type.edit_form');
}