<?php

/**
 * @file
 *
 */

/**
 * Implements hook_menu().
 */
function crm_core_match_menu() {
  $items['admin/config/crm-core/match'] = array(
    'title' => 'Match configuration',
    'description' => 'Settings page listing match engines in order they would be applied.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('crm_core_match_admin_config_engines_form'),
    'access callback' => TRUE,
    'file' => 'crm_core_match.admin.inc',
  );

  $items['admin/config/crm-core/match/engines'] = array(
    'title' => 'Engines',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  foreach (crm_core_contact_types() as $type => $info) {
    $items['admin/config/crm-core/match/' . $type . '/edit'] = array(
      'title' => 'Matching Rules for @type',
      'title arguments' => array('@type' => $info->name),
      'description' => 'Matching Rules for %type',
      'description arguments' => array('%type' => $info->name),
      'page callback' => '_crm_core_match_ui_placeholder',
      'access callback' => TRUE,
      'file' => 'crm_core_match.admin.inc',
    );
  }

  return $items;
}

function _crm_core_match_ui_placeholder() {
  return 'CRM Core Match UI would be here soon!';
}
