<?php

/**
 * @file
 * Manages matching engines for identifying duplicate contacts in CRM Core.
 * Allows CRM Core to install, enable and disable matching engines.
 * 
 * A matching engine is used to do the following:
 * 
 * - identify duplicate contact records
 * - inject data into contact records being saved
 * - carry out other scripted operations not easily handled in the normal bootstrapping process
 * 
 * This module does not define any matching engines itself, it only provides the framework
 * through which they can be applied to new contacts being created in the database.
 * 
 * @TODO: add hooks for altering the submission process
 */

/**
 * Implements hook_hook_info().
 */
function crm_core_match_hook_info() {
  $hooks = array(
    'crm_core_match_engine_register' => array(
      'group' => 'crm_core_match',
    ),
  );

  return $hooks;
}

/**
 * Implements hook_menu().
 * 
 * @todo: this needs to change...
 * - there should be a second module
 * - call it default matching engine
 * - this is where the links for the matching engine will be defined
 * - these links might need to be defined as part of the entity
 * - which entity?
 * 
 */
function crm_core_match_menu() {
  $items['admin/config/crm-core/match'] = array(
    'title' => 'Matching Engines',
    'description' => 'Configure the default rules for matching duplicate contacts in CRM Core.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('crm_core_match_admin_config_engines_form'),
    'access callback' => TRUE,
    'file' => 'crm_core_match.admin.inc',
  );

  $items['admin/config/crm-core/match/engines'] = array(
    'title' => 'Engines',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  return $items;
}

/**
 * Implements hook_theme
 */
function crm_core_match_theme() {
  return array(
    'crm_core_match_admin_config_engines_form' => array(
      'render element' => 'form',
      'file' => 'crm_core_match.admin.inc',
    ),
  );
}

/**
 * Implements hook_crm_core_match_engine_register
 * 
 * @todo: remove this once we are done testing
 * 
 */
function crm_core_match_crm_core_match_engine_register(){
  
  $info = new stdClass();
  $info->name = '(test) CRM Core Match Engine';
  $info->machine_name = 'test_matching_engine';
  $info->description = 'This is just a test, to see how matching engines show up in CRM Core Match. Remove this from CRM Core Match before the module is launched.';
  $info->settings = array(
    array('path' => '<front>', 'label' => 'Test Settings Page', 'name' => 'settings'),
    array('path' => '<front>', 'label' => 'Other Test Settings Page', 'name' => 'settings2'),
  );
  
  $test = new DefaultMatchingEngine($info);
  return $test->matchEngineInfo();
  
}



