<?php 

/**
 * @file
 * The default matching engine for CRM Core.
 * Identifies duplicate contacts in the system using criteria
 * defined by users through the configuration tools.
 */

/**
 * Implements hook_permissions
 */
function crm_core_default_matching_engine_permission() {
  return array(
    'modify default matching engine rules' => array(
      'title' => t('Modify default matching engine rules'),
      'description' => t('Allow users to modify the rules associated with the CRM Core Match default matching engine.'),
    ),
  );
}



/**
 * Implements hook_menu().
 * 
 * @TODO: improve this, way too many links appearing on the config page
 * 
 * @TODO: links should point to something in the structure section
 *   - this is too important
 * 
 */
function crm_core_default_matching_engine_menu() {
  
  foreach (crm_core_contact_types() as $type => $info) {
    $items['admin/config/crm-core/default_match/' . $type . '/edit'] = array(
      'title' => 'Matching Rules for @type',
      'title arguments' => array('@type' => $info->name),
      'description' => 'Matching Rules for %type',
      'description arguments' => array('%type' => $info->name),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('crm_core_default_matching_engine_form', 4),
      'access arguments' => array('modify default matching engine rules'),
      'file' => 'crm_core_default_matching_engine.admin.inc',
    );
  }
  return $items;
}


/**
 * Implements hook_crm_core_match_engine_register
 */
function crm_core_default_matching_engine_crm_core_match_engine_register(){
  
  $info = new stdClass();
  $info->name = 'Default Matching Engine';
  $info->machine_name = 'default_matching_engine';
  $info->description = 'This is a simple matching engine from CRM Core. Allows administrators to specify matching rules for individual contact types on a field-by-field basis.';
  $info->settings = array();
  $default = new DefaultMatchingEngine($info);
  return $default->matchEngineInfo();
  
}

/**
 * Implements hook_theme
 */
function crm_core_default_matching_engine_theme() {
  return array(
    'crm_core_default_matching_engine_form' => array(
      'render element' => 'form',
      'file' => 'crm_core_default_matching_engine.admin.inc',
    ),
  );
}