<?php 


/**
 * Implements hook_crm_core_match_engine_register
 */
function crm_core_default_matching_engine_crm_core_match_engine_register(){
  
  $info = new stdClass();
  $info->name = 'Default Matching Engine';
  $info->machine_name = 'default_matching_engine';
  $info->description = 'This is the default matching engine from CRM Core.';
  $info->settings = array();
  $default = new DefaultMatchingEngine($info);
  return $default->matchEngineInfo();
  
}



