<?php

/**
 * @file
 * Install, update, and uninstall functions for the CRM Core Default Matching Engine module.
 */

use Drupal\crm_core_contact\Entity\ContactType;

/**
 * Implements hook_install().
 *
 * Add matching rules for all existing contact types.
 */
function crm_core_default_matching_engine_install() {
  $contact_types = ContactType::loadMultiple();
  foreach ($contact_types as $type) {
    crm_core_default_matching_engine_entity_insert($type);
  }
}
