# Schema for the configuration files of the crm_core_activity module.

crm_core_activity.type.*:
  type: config_entity
  label: 'Activity type'
  mapping:
    name:
      type: label
      label: 'Name'
    type:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    activity_string:
      type: string
      label: 'Text describing the relationship between the contact and this activity.'
